### ISSUE TITLE
Front-end for website

### ISSUE THREAD

**Issue by hitiksaini** [hitiksaini/Blog-Website#4]
Currently the website is just a prototype (no styling is done). 

Goal: Create a minimal design as a front-end to this project.

**Comment by NicolaDeastra** [comment]
Hi, @hitiksaini can I take this issue ?, but I only can use a template engine.

**Comment by hitiksaini** [comment]
Hey! @NicolaDonoastro , Impressive work! I've merged your PR to the project.
